version: '3'

services:
  mysql:
    image: mysql:8
    container_name: hapi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: hapi
      MYSQL_DATABASE: user
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
